flyway.url=jdbc:postgresql://mirante-pg:5432/codeAgent
flyway.user=mirante
flyway.password=mirante2025pass
flyway.locations=filesystem:/flyway/sql
flyway.baselineOnMigrate=true
flyway.baselineVersion=1
flyway.schemas=public
flyway.connectRetries=10
flyway.cleanDisabled=true
